# Generated by Django 4.1.4 on 2022-12-27 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_pedido', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('descri_foto', models.ImageField(blank=True, upload_to='')),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('estado_pedido', models.CharField(blank=True, choices=[('Ingresado', 'Ingresado'), ('En proceso', 'En proceso'), ('Listo', 'Listo'), ('Entregado', 'Entregado')], default='Ingresado', max_length=15)),
                ('estado_saldo', models.CharField(choices=[('Sin seña', 'Sin seña'), ('Señado', 'Señado'), ('Pagado', 'Pagado')], default='Sin seña', max_length=10)),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('apellido', models.CharField(default='', max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=30)),
                ('provincia', models.CharField(blank=True, max_length=40)),
                ('ciudad', models.CharField(blank=True, max_length=40)),
                ('domicilio', models.CharField(blank=True, max_length=80)),
                ('codigo_postal', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('documento', models.CharField(blank=True, max_length=30)),
                ('cuit', models.CharField(blank=True, max_length=30)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
