# Generated by Django 4.1.4 on 2022-12-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_order_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='descripcion',
            field=models.CharField(default='NO TIENE DECRIPCION O ES NUEVO', max_length=200),
        ),
    ]
