# Generated by Django 4.1.4 on 2022-12-29 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_cliente_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['fecha_ingreso'], 'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
    ]
