# Generated by Django 4.1.4 on 2023-03-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_order_id_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
