# Generated by Django 4.1.4 on 2023-03-09 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('pedidos', '0007_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.clienteusuario'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_pedido',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
