# Generated by Django 4.1.4 on 2023-03-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_alter_order_id_cliente_alter_order_id_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
