# Generated by Django 4.1.4 on 2023-03-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['fecha_ingreso'], 'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
    ]
