# Generated by Django 4.1.4 on 2023-03-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_clienteusuario_documento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienteusuario',
            old_name='usuario',
            new_name='username',
        ),
    ]
