# Generated by Django 4.1.4 on 2023-03-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_rename_usuario_clienteusuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteusuario',
            name='email',
            field=models.EmailField(default='dirección de email', max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
